name: Test and lint
on: [push]
jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: 
          bundle install
          yarn install
      - name: Run linter
        run:
          rubocop
      - name: Run tests
        run:
          bin/rails test